# SPDX-FileCopyrightText: 2021 David Ruescas <david@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "b3"
version = "0.1.0"
authors = [
  "David Ruescas <david@sequentech.io>",
  "Eduardo Robles <edu@sequentech.io>"
]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
strand = { path="../strand", features=["rayon"] }
borsh = { version = "=1.5", features = ["derive"] }
strum = { version = "0.27", features = ["derive"] }
anyhow = "1.0"
rayon = "1.5"

# only needed to use the postgresql COPY command (sqlcopy feature)
futures = { version = "0.3", optional = true }

# only needed for the server component
config = { version = "0.15", optional = true }

# logging
log = "0.4"
tracing = "0.1"
tracing-log = "0.2"
tracing-attributes = "0.1"
tracing-subscriber = "0.3"
tracing-tree = "0.4"

cfg-if = "1.0"

hex = "0.4"
base64 = "0.22"
serde = "1.0"
toml = "0.8"

tonic = "0.13"
prost = "0.13"
tokio = { version = "1.38", features = ["full"] }
tokio-postgres = "0.7"
bb8-postgres = "0.9"

clap = { version = "4.0", features = ["derive"] }
# cursive = { version = "0.21.1", optional = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# monitor = ["dep:cursive"]
sqlcopy = ["dep:futures"]
client = []
server = ["client", "dep:config"]

[build-dependencies]
tonic-build = "0.13"

[dev-dependencies]
serial_test = "3.2"
