# SPDX-FileCopyrightText: 2021 David Ruescas <david@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "b3"
version = "0.1.0"
authors = [
  "David Ruescas <david@sequentech.io>",
  "Eduardo Robles <edu@sequentech.io>"
]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
strand = { path="../strand", features=["rayon"] }
borsh = { version = "=1.5.1", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
anyhow = "1.0"
rayon = "1.5"

# only needed to use the postgresql COPY command (sqlcopy feature)
futures = { version = "0.3", optional = true }

# only needed for the server component
config = { version = "0.13", optional = true }

# logging
log = "0.4.17"
tracing = "0.1"
tracing-log = { version = "0.1.3" }
tracing-attributes = "0.1.23"
tracing-subscriber = "0.3.16"
tracing-tree = "0.2.1"

cfg-if = "1.0"

hex = "0.4.2"
base64 = "0.22.1"
serde = "1.0.152"
toml = "0.6.0"

tonic = "0.12"
prost = "0.13"
tokio = { version = "1.38.1", features = ["full"] }
tokio-postgres = "0.7.10"
bb8-postgres = "0.8.1"

clap = { version = "4.0", features = ["derive"] }
# cursive = { version = "0.21.1", optional = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# monitor = ["dep:cursive"]
sqlcopy = ["dep:futures"]
client = []
server = ["client", "dep:config"]

[build-dependencies]
tonic-build = "0.12.3"

[dev-dependencies]
serial_test = "2.0.0"
