# SPDX-FileCopyrightText: 2024 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "doc_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
# common library for sequent lambdas
orare = { path = ".." }

# dependencies required by the procedural macro in orare
bytes = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cfg-if = "1.0"
anyhow = { version = "1", features = ["backtrace"] }
base64 = "0.21.0"
headless_chrome = { version = "1.0.15", default-features = false }
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
warp = "0.3"
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }

# for rendering we use sequent core functionality
sequent-core = { path = "../../sequent-core", features = ["reports", "log", "areas", "pdf-inplace"] }

lambda_runtime = { version = "0.13" }

[features]
default = ["openwhisk"]
aws_lambda = ["orare/aws_lambda", "sequent-core/pdf-lambda"]
openwhisk = ["orare/openwhisk", "sequent-core/pdf-openwhisk"]
openwhisk-dev = ["orare/openwhisk-dev", "sequent-core/pdf-openwhisk-dev"]
inplace = ["orare/inplace", "sequent-core/pdf-inplace"]