name: Generate API Documentation

on:
  push:
    branches:
      - feat/meta-1148A/main

jobs:
  generate-docs:
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Generate documentation
      run: yarn run generate-full-docs

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packages/api-docs/graphql/docs