# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: 'CI | Lint'
on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  lint:
    name: 'Lint'
    uses: sequentech/meta/.github/workflows/lint.yml@main
    with:
      cachix-auth-identity: '${{ vars.CACHIX_AUTH_IDENTITY }}'
      rust: true
    secrets:
      cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
