# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: 'CI | Nix Register Flake Info'
on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  nix-register-flake:
    name: 'Nix Register Flake Info'
    uses: sequentech/meta/.github/workflows/nix-register-flake.yml@main
    with:
      cachix-auth-identity: '${{ vars.CACHIX_AUTH_IDENTITY }}'
    secrets:
      cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
