# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: 'CI | REUSE'
on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  code-coverage:
    name: 'REUSE'
    uses: sequentech/meta/.github/workflows/reuse.yml@main
    with:
      cachix-auth-identity: '${{ vars.CACHIX_AUTH_IDENTITY }}'
    secrets:
      cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
