[package]
name = "velvet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
rand = "0.8.5"
sequent-core = { path="../sequent-core" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["strum_macros"] }
strum_macros = "0.25.2"

[dev-dependencies]
anyhow = "1"
sequent-core = { path="../sequent-core" }
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
