# SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "velvet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "velvet"
path = "src/lib.rs"

[[bin]]
name = "velvet"
path = "src/main.rs"
# Do not run lib tests twice
test = false

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rand = "0.9"
sequent-core = { path="../sequent-core", features=["reports", "reports_sync", "log", "areas", "signatures", "sqlite"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.27", features = ["strum_macros"] }
strum_macros = "0.27"
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }
num-bigint = { version = "0.4", features = ["rand"] }
anyhow = "1" # FIXME: To be removed
strand = { path="../strand" }
csv = "1.3"
tokio = { version = "1.32", features = ["full"] }
walkdir = "2"

# logging
tracing = "0.1"
rayon = "1.8"
criterion = "0.5"

# serializing
hex = "0.4"

# sqlite
rusqlite = { version = "0.32", features = ["bundled"] }
tempfile = "3.15.0"
ordered-float = { version = "4.4.0", features = ["serde"] }

[dev-dependencies]
anyhow = "1"

[[bench]]
name = "pdf_generation"
harness = false
