# SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "velvet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "velvet"
path = "src/lib.rs"

[[bin]]
name = "velvet"
path = "src/main.rs"
# Do not run lib tests twice
test = false

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
rand = "0.8.5"
sequent-core = { path="../sequent-core", features=["reports", "reports_sync", "log", "areas", "signatures"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["strum_macros"] }
strum_macros = "0.25.2"
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "serde"] }
num-bigint = { version = "0.4", features = ["rand"] }
anyhow = "1" # FIXME: To be removed
strand = { path="../strand" }
csv = "1.3.0"
tokio = { version = "1.32.0", features = ["full"] }

# logging
tracing = "0.1"
rayon = "1.8.0"
criterion = "0.5.1"

# serializing
hex = "0.4"

# sqlite
rusqlite = { version = "0.32", features = ["bundled"] }
tempfile = "3.15.0"

[dev-dependencies]
anyhow = "1"
walkdir = "2"

[[bench]]
name = "pdf_generation"
harness = false
