table:
    name: applications
    schema: sequent_backend
insert_permissions:
    - role: admin-user
      permission:
          check:
              _and:
                  - tenant_id:
                        _eq: X-Hasura-Tenant-Id
                  - _or:
                        - permission_label:
                              _is_null: true
                        - permission_label:
                              _in: X-Hasura-Permission-Labels
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
      comment: ""
    - role: application-write
      permission:
          check:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
      comment: ""
    - role: service-account
      permission:
          check: {}
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
      comment: ""
select_permissions:
    - role: admin-user
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              _and:
                  - tenant_id:
                        _eq: X-Hasura-Tenant-Id
                  - _or:
                        - permission_label:
                              _is_null: true
                        - permission_label:
                              _in: X-Hasura-Permission-Labels
          allow_aggregations: true
      comment: ""
    - role: application-read
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          allow_aggregations: true
      comment: ""
    - role: application-write
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          allow_aggregations: true
      comment: ""
    - role: service-account
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter: {}
          allow_aggregations: true
      comment: ""
update_permissions:
    - role: admin-user
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          check: null
      comment: ""
    - role: application-write
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          check: null
      comment: ""
    - role: service-account
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter: {}
          check: {}
      comment: ""
delete_permissions:
    - role: admin-user
      permission:
          filter:
              _and:
                  - tenant_id:
                        _eq: X-Hasura-Tenant-Id
                  - _or:
                        - permission_label:
                              _is_null: true
                        - permission_label:
                              _in: X-Hasura-Permission-Labels
      comment: ""
    - role: application-write
      permission:
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      comment: ""
    - role: service-account
      permission:
          filter: {}
      comment: ""
