table:
    name: applications
    schema: sequent_backend
insert_permissions:
    - comment: ""
      permission:
          check:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          columns:
              - annotations
              - applicant_data
              - applicant_id
              - area_id
              - created_at
              - election_event_id
              - id
              - labels
              - status
              - tenant_id
              - updated_at
              - verification_type
      role: admin-user
    - comment: ""
      permission:
          check:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
      role: application-write
    - comment: ""
      permission:
          check: {}
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
      role: service-account
select_permissions:
    - comment: ""
      permission:
          allow_aggregations: true
          columns:
              - annotations
              - applicant_data
              - applicant_id
              - area_id
              - created_at
              - election_event_id
              - id
              - labels
              - permission_label
              - status
              - tenant_id
              - updated_at
              - verification_type
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      role: admin-user
    - comment: ""
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      role: application-read
    - comment: ""
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      role: application-write
    - comment: ""
      permission:
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter: {}
      role: service-account
update_permissions:
    - comment: ""
      permission:
          check:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      role: admin-user
    - comment: ""
      permission:
          check:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      role: application-write
    - comment: ""
      permission:
          check: {}
          columns:
              - applicant_id
              - status
              - verification_type
              - annotations
              - applicant_data
              - labels
              - permission_label
              - created_at
              - updated_at
              - area_id
              - election_event_id
              - id
              - tenant_id
          filter: {}
      role: service-account
delete_permissions:
    - comment: ""
      permission:
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      role: admin-user
    - comment: ""
      permission:
          filter:
              tenant_id:
                  _eq: X-Hasura-Tenant-Id
      role: application-write
    - comment: ""
      permission:
          filter: {}
      role: service-account
