# // SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
# //
# // SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "step-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.8", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
strum = "0.26"
strum_macros = "0.26"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
graphql_client = "0.14.0"
rayon = "1.5"
sequent-core = { path="../sequent-core", features = ["keycloak", "probe", "reports"] }
windmill = { path="../windmill" }
strand = { path="../strand" }
immudb-rs = { path="../immudb-rs" }
electoral-log = { path="../electoral-log" }

uuid = { version = "1.5.0", features = ["v4", "fast-rng"] }
fake = { version = "4", features = ["derive"] }
csv = "1.1"
rand = "0.8"
chrono = "0.4"
tokio = { version = "1.38.1", features = ["full"] }
tokio-postgres = "0.7.10"
deadpool-postgres = { version = "0.11.0", features = ["rt_tokio_1", "serde"] }

hex = "0.4"
ring = "0.17"
sha2 = "0.10"
base64 = "0.21.0"
[[bin]]
name = "step-cli"
path = "src/main.rs"
