# // SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
# //
# // SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "step-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.8", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.25"
strum_macros = "0.25"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
graphql_client = "0.13.0"
sequent-core = { path="../sequent-core", features = ["keycloak", "probe", "reports"] }
windmill = { path="../windmill" }

[[bin]]
name = "seq"
path = "src/main.rs"