# SPDX-FileCopyrightText: 2023 Eduardo Robles <edu@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "immudb-rs"
version = "0.1.0"
edition = "2021"
authors = [
  "Eduardo Robles <edu@sequentech.io>"
]
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0"
tonic = { version = "0.12.3" }
prost = { version = "0.13.5" }
prost-types = { version = "0.13.5" }
serde = "1.0.152"

# logging 
log = "0.4.17"
tracing = "0.1"
tracing-log = { version = "0.1.3" }
tracing-attributes = "0.1.23"
tracing-subscriber = "0.3.16"
tracing-tree = "0.2.1"


[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
tonic-build = "0.12.3"
