# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "immudb-rs"
version = "0.1.0"
edition = "2021"
authors = [
  "Eduardo Robles <edu@sequentech.io>"
]
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0"
tonic = "0.13"
prost = { version = "0.13" }
prost-types = { version = "0.13" }
serde = "1.0"

# logging 
log = "0.4"
tracing = "0.1"
tracing-log = "0.2"
tracing-attributes = "0.1"
tracing-subscriber = "0.3"
tracing-tree = "0.4"


[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
tonic-build = "0.13"
