# SPDX-FileCopyrightText: 2023 Eduardo Robles <edu@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
[package]
name = "wrap-map-err"
version = "0.1.0"
edition = "2021"
authors = [
  "Eduardo Robles <edu@sequentech.io>"
]
license = "AGPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0", features = ['full'] }
quote = "1.0"
proc-macro2 = "1.0"
