# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "immu-board"
version = "0.1.0"
edition = "2021"
authors = [
  "David Ruescas <david@sequentech.io>",
  "Eduardo Robles <edu@sequentech.io>"
]
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
immudb-rs = { path="../immudb-rs" }
tokio = { version = "1.31", features = ["rt-multi-thread"]}
tonic = "0.13"
hex = "0.4"

# logging 
log = "0.4"
tracing = "0.1"
tracing-log = "0.2"
tracing-attributes = "0.1"
tracing-subscriber = "0.3"
tracing-tree = "0.4"

[dev-dependencies]
serial_test = "3.2"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
tonic-build = "0.13"
