# SPDX-FileCopyrightText: 2022 Felix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
[package]
name = "new-ballot-verifier-lib"
version = "0.1.0"
edition = "2021"
authors = [
  "Felix Robles <felix@sequentech.io>"
]
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]
path = "rust/src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# wasm
wasm-bindgen = {version = "=0.2.79", features = ['serde-serialize'], optional = true}
serde-wasm-bindgen = "0.4"
web-sys = { version = "0.3.4", features = ['Performance'], optional = true}
cfg-if = "1.0.0"

# error logging
console_error_panic_hook = "0.1.7"

# parent packages
sequent-core = { path="../sequent-core", features = ['wasm']}
strand = { path="../strand", features = ['num_bigint']}

[features]
wasmtest = ["wasm", "dep:web-sys"]
wasm = ["wasm-bindgen"]
default = ["wasmtest"]
