# SPDX-FileCopyrightText: 2021 David Ruescas <david@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "board-messages"
version = "0.1.0"
authors = [
  "David Ruescas <david@sequentech.io>",
  "Eduardo Robles <edu@sequentech.io>"
]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
strand = { path="../strand", features=["rayon"] }
immu-board = { path="../immu-board" }
borsh = "0.9.3"
strum = { version = "0.24.1", features = ["derive"] }
anyhow = "1.0"

# logging 
log = "0.4.17"
tracing = "0.1"
tracing-log = { version = "0.1.3" }
tracing-attributes = "0.1.23"
tracing-subscriber = "0.3.16"
tracing-tree = "0.2.1"

cfg-if = "1.0"
config = {version = "0.13.1" }
hex = "0.4.2"
base64 = "0.21.0"
serde = "1.0.152"
toml = "0.6.0"

tonic = "0.12.1"
prost = "0.13.1"
tokio = { version = "1.38.1", features = ["full"] }
tokio-postgres = "0.7.10"

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[build-dependencies]
tonic-build = "0.12.1"

[dev-dependencies]
serial_test = "2.0.0"