[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/rusty-celery/rusty-celery.git?rev=1a0168f4b4b521c891fcfc853c21fc30de12c2f2"]
git = "https://github.com/rusty-celery/rusty-celery.git"
rev = "1a0168f4b4b521c891fcfc853c21fc30de12c2f2"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"