# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[workspace]

members = [
    "strand",
    "braid",
    "b3",
    "immu-board",
    "immudb-rs"
]