signing_key_sk = "MC4CAQAwBQYDK2VwBCIEIPNjpAbBa2Y4N30nqqeJbq0FMpFeLyeskHRZINObAPab"
signing_key_pk = "MCowBQYDK2VwAyEAJHGkHnzO7iumO4VsNDAhIAoBbZeNsIgYzecbQt0UTy0="
encryption_key = "zDH4NIsidpL1pxp3AnsZpyD5YwTw5axeRMWn83ZmyqM"
