# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Build WASM Target

on:
  push:
    branches: [ 'main', 'feat/meta-2881/main' ]

jobs:
  build_wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: mycache
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix-build

      - run: nix-shell --run "echo OK"

      - name: Install wasm-pack via Nix
        run: nix-env -iA nixpkgs.wasm-pack

      - name: Build WASM Target
        run: wasm-pack build --mode no-install --out-name index --release --target web --features=wasmtest

      - name: Package WASM for npm
        run: wasm-pack -v pack .