# SPDX-FileCopyrightText: 2022 Felix Robles <felix@sequentech.io>
# SPDX-FileCopyrightText: 2024 Eduardo Robles <edu@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
[package]
name = "sequent-core"
version = "0.1.0"
edition = "2021"
authors = [
  "Felix Robles <felix@sequentech.io>"
]
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[[example]]
name = "render_pdf"
required-features = ["reports"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serialization
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_path_to_error = "0.1"
# borsh = "0.9.3"
borsh = { version = "1.5", features = ["derive"] }
# wasm
wasm-bindgen = {version = "=0.2.95", features = ['serde-serialize'], optional = true}
serde-wasm-bindgen = { version = "0.6", optional = true }
web-sys = { version = "0.3.4", features = ['Performance', 'console'], optional = true}
cfg-if = "1.0"
# signatures
ed25519-dalek = {version = "=2.1.1", features = ["serde"]}
curve25519-dalek = { version = "=4.1.2", features = [] }

# aws
aws-config = { version = "1.6.0", features = ["behavior-version-latest"], optional = true }
aws-sdk-sesv2 = { version = "1.70.0", optional = true }
aws-sdk-sns = { version = "1.63.0", optional = true }

# for s3
aws-sdk-s3 = { version = "1.79.0", optional = true }
aws-smithy-types = { version = "1.3.0", optional = true }
sha256 = { version = "1.6", optional = true }

# time
chrono = { version = "0.4", features = ["serde"] }

# time
time = { version = "0.3.31", optional = true }

# serializing
hex = "0.4"
base64 = "0.22.1"

# rust to json schema
schemars = { version = "0.8", features = ["chrono"]}
# strand
strand = { path="../strand", features = ["num_bigint"]}
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
quick-error = "2.0.0"

strum = "0.26"
strum_macros = "0.26"

# error logging
console_error_panic_hook = "0.1.7"

# error handling
anyhow = "1.0.75"

# character mapping for write-ins
phf = { version = "0.11", features = ["macros"], default-features = false }

# template system
handlebars = { version = "6.1.0", optional = true }
handlebars-chrono = { version = "0.2.1", features = [ "locale", "timezone" ], optional = true }
num-format = { version = "0.4.4", optional = true }
headless_chrome = { version = "1.0.12", default-features = false, optional = true }
reqwest = { version="0.12", features = ["blocking", "json"], optional = true }
reqwest-retry = { version = "0.7.0", optional = true }
reqwest-middleware = { version = "=0.3.1", optional = true }
# logging
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3.16", optional = true }
tracing-tree = { version = "0.4.0", optional = true }
tracing-log = { version = "0.2.0", optional = true }

tempfile = { version = "3.8.0", optional = true }
keycloak = { version = "26.0.200", optional = true }

# openid connection
openid = { version = "0.15.0", optional = true }
serde_urlencoded = { version = "0.7.1", optional = true }
rocket = { version = "0.5.0", features = ["json"], optional = true }
uuid = { version = "1.5.0", features = ["v4", "fast-rng"], optional = true }
regex = { version = "1.10.2", optional = true }
jsonwebtoken = { version = "9.1.0", optional = true }

# For converting rows into users
tokio-postgres = { version = "0.7", features = ["with-uuid-1", "with-chrono-0_4", "with-serde_json-1"], optional = true }

# probehandler
tokio = { version = "1.44", features = ["full"], optional = true }
warp =  { version = "0.3", optional = true }
ammonia = "4.0.0"

rand = "0.8"

# for lambda/openwhisk
async-trait = { version = "0.1", optional = true }

printpdf = { version = "0.7.0", optional = true }
kuchiki = { version = "0.8.1", optional = true }

# sqlite
rusqlite = { version = "0.32", features = ["bundled"], optional = true }
csv = "1.3.0"

[dev-dependencies]
ptree = "0.5.0"

[features]
wasmtest = ["wasm", "dep:web-sys", "strand/wasmtest"]
wasm = ["wasm-bindgen", "areas", "serde-wasm-bindgen"]
signatures=["dep:tracing"]
default = []
areas = []
reports = ["dep:handlebars", "dep:handlebars-chrono", "dep:headless_chrome", "dep:reqwest", "dep:tracing", "dep:tokio", "dep:num-format", "dep:aws-config", "dep:aws-sdk-sesv2", "dep:aws-sdk-sns", "dep:aws-sdk-s3", "dep:aws-smithy-types", "dep:sha256"]
reports_sync = []
s3 = ["dep:reqwest"]
keycloak = ["dep:openid", "dep:reqwest", "dep:reqwest-retry", "dep:reqwest-middleware", "dep:serde_urlencoded", "dep:rocket", "dep:keycloak", "dep:tracing", "dep:uuid", "dep:regex", "dep:jsonwebtoken", "dep:tokio-postgres", "dep:time"]
log = ["dep:tracing", "dep:tracing-subscriber", "dep:tracing-tree", "dep:tracing-log"]
probe = ["dep:tokio", "dep:warp"]
# Lambda examples
lambda_inplace = []
lambda_openwhisk = []
lambda_aws_lambda = []
sqlite = ["dep:tokio", "dep:rusqlite"]