# SPDX-FileCopyrightText: 2022 Felix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
[package]
name = "sequent-core"
version = "0.1.0"
edition = "2021"
authors = [
  "Felix Robles <felix@sequentech.io>"
]
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "0.9.3"
# wasm
wasm-bindgen = {version = "=0.2.79", features = ['serde-serialize'], optional = true}
serde-wasm-bindgen = "0.4"
web-sys = { version = "0.3.4", features = ['Performance'], optional = true}
cfg-if = "1.0"
# signatures
ed25519-dalek = {version = "1", features = ["serde"]}

# time
chrono = "0.4"

# serializing
hex = "0.4"
base64 = "0.21.0"

# rust to json schema
schemars = "0.8"
# strand
strand = { path="../strand", features = ["num_bigint"]}
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
quick-error = "2.0.0"

strum = "0.25"
strum_macros = "0.25"

# error logging
console_error_panic_hook = "0.1.7"

# error handling
anyhow = "1.0.75"

# character mapping for write-ins
phf = { version = "0.11", features = ["macros"], default-features = false }

# template system
handlebars = { version = "4.3.7", optional = true }
headless_chrome = { version = "1.0.5", default-features = false, optional = true }
reqwest = { version="0.11.18", features = ["blocking", "json"], optional = true }
# logging
tracing = { version = "0.1.37", optional = true }
tracing-subscriber = { version = "0.3.16", optional = true }
tracing-tree = { version = "0.2.1", optional = true }
tracing-log = { version = "0.1.3", optional = true }

tempfile = { version = "3.8.0", optional = true }
keycloak = { version = "21.0.102", optional = true }

# immu-board = { path="../immu-board", optional = true }
# immudb-rs = { path="../immudb-rs", optional = true }

# openid connection
openid = { version = "0.12.1", optional = true }
serde_urlencoded = { version = "0.7.1", optional = true }
rocket = { version = "0.5.0", features = ["json"], optional = true }
uuid = { version = "1.5.0", features = ["v4", "fast-rng"], optional = true }
regex = { version = "1.10.2", optional = true }
jsonwebtoken = { version = "9.1.0", optional = true }

# For converting rows into users
tokio-postgres = { version = "0.7", features = ["with-uuid-1", "with-chrono-0_4"] }

[dev-dependencies]
rand = { package="rand", version = "0.8" }

[features]
wasmtest = ["wasm", "dep:web-sys", "strand/wasmtest"]
wasm = ["wasm-bindgen"]
default = []
reports = ["dep:handlebars", "dep:headless_chrome", "dep:tracing", "dep:tempfile"]
keycloak = ["dep:openid", "dep:reqwest", "dep:serde_urlencoded", "dep:rocket", "dep:keycloak", "dep:uuid", "dep:regex", "dep:jsonwebtoken"]
log = ["dep:tracing", "dep:tracing-subscriber", "dep:tracing-tree", "dep:tracing-log"]
# boards = ["dep:immu-board"]
