# SPDX-FileCopyrightText: 2023 Eduardo Robles <edu@sequentech.io>
# 
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "harvest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
serde = "1.0.174"
reqwest = { version="0.11.18", features = ["blocking", "json"] }
handlebars = "4.3.7"
headless_chrome = {version = "1.0.5", default-features = false}
anyhow = "1.0.75"
tempfile = "3.8.0"
either = "1.9.0"
dotenv = "0.15.0"
graphql_client = "0.13.0"
serde_json = "1.0.105"
rust-s3 = "0.33.0"
tokio = { version = "1.32.0", features = ["full"] }
chrono = "0.4.31"
base64 = "0.21.0"

strum = "0.25"
strum_macros = "0.25"

# logging
tracing = "0.1.37"

immu-board = { path="../immu-board" }
immudb-rs = { path="../immudb-rs" }
braid = { path="../braid" }
strand = { path="../strand" }
sequent-core = { path="../sequent-core" }

