# SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "electoral-log"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
immudb-rs = { path="../immudb-rs" }
borsh = { version = "=1.5.1", features = ["derive"] }
anyhow = "1.0.75"
strand = { path="../strand" }
serde = { version = "1.0.190", features = ["derive"] }
strum = "0.25"
strum_macros = "0.25"
tokio = { version = "1.38.1", features = ["test-util", "rt-multi-thread"] }
tokio-stream = "0.1.17"
tonic = "0.12"
hex = "0.4.3"
serde_json = "1.0"

# logging 
log = "0.4.17"
tracing = "0.1"
tracing-log = { version = "0.1.3" }
tracing-attributes = "0.1.23"
tracing-subscriber = "0.3.16"
tracing-tree = "0.2.1"

[dev-dependencies]
serial_test = "2.0.0"
