# SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "electoral-log"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
immudb-rs = { path="../immudb-rs" }
borsh = { version = "=1.5", features = ["derive"] }
anyhow = "1.0"
strand = { path="../strand" }
serde = { version = "1.0", features = ["derive"] }
strum = "0.27"
strum_macros = "0.27"
tokio = { version = "1.38", features = ["test-util", "rt-multi-thread"] }
tonic = "0.13"
hex = "0.4"
serde_json = "1.0"

# logging 
log = "0.4"
tracing = "0.1"
tracing-log = "0.2"
tracing-attributes = "0.1"
tracing-subscriber = "0.3"
tracing-tree = "0.4"

[dev-dependencies]
serial_test = "3.2"
