# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[workspace]
resolver = "2"

members = [
    "braid",
    "b3",
    "electoral-log",
    "harvest",
    "strand",
    "immu-board",
    "immudb-rs",
    "sequent-core",
    "velvet",
    "windmill",
    "wrap-map-err",
    "step-cli",
    "e2e/src/mock_server",
    "e2e",
    "orare",
    "orare/doc_renderer"
, "plugins/*"]

[patch.crates-io]
celery = { git = "https://github.com/rusty-celery/rusty-celery.git", rev = "1a0168f4b4b521c891fcfc853c21fc30de12c2f2" }

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
