[workspace]

members = [
    "braid",
    "harvest",
    "strand",
    "immu-board",
    "immudb-rs",
    "sequent-core",
    "ballot-verifier",
    "braid-messages",
    "velvet",
    "windmill",
    "wrap-map-err",
]
