# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

[workspace]
resolver = "2"

members = [
    "braid", 
    "b3",
    "electoral-log",
    "harvest",
    "strand",
    "immu-board",
    "immudb-rs",
    "sequent-core",
    "velvet",
    "windmill",
    "wrap-map-err",
    "step-cli"
]
