name: Build WASM Target

on:
  pull_request:
  push:
    branches: [ 'main' ]
  release:
    types: [published]

jobs:
  build_wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use nix develop to build WASM
        working-directory: packages/sequent-core
        run: |
          nix develop --command wasm-pack build --mode no-install --out-name index --release --target web --features=wasmtest

      - name: Pack WASM
        working-directory: packages/sequent-core
        run: |
          nix develop --command wasm-pack -v pack . 2>&1 | tee output.log

      - name: Check that hashes in yarn.lock are updated
        working-directory: packages
        run: |
          if [ -f yarn.lock ] && [ -f sequent-core/output.log ]; then
            hash=$(grep "shasum:" sequent-core/output.log | awk '{printf $4}')
            hash1=$(grep "file:./admin-portal/rust/sequent-core-" yarn.lock | awk -F# '{printf $2}' | tr -d '"')
            hash2=$(grep "file:./ballot-verifier/rust/sequent-core-" yarn.lock | awk -F# '{printf $2}' | tr -d '"')
            hash3=$(grep "file:./voting-portal/rust/sequent-core-" yarn.lock | awk -F# '{printf $2}' | tr -d '"')
            echo "Hashes: |$hash| |$hash1| |$hash2| |$hash3|"
            if ([ -n "$hash" ] && [ -n "$hash1" ] && [ -n "$hash2" ] && [ -n "$hash3" ]); then
              if ([ "$hash" == "$hash1" ] && [ "$hash" == "$hash2" ] && [ "$hash" == "$hash3" ]); then
                echo "The hashes are equal"
              else
                echo "The hashes are not equal"
                exit 1
              fi
            else
              echo "Error: unable to extract hashes from files"
              exit 1
            fi
          else
            echo "Error: one or both files do not exist"
            exit 1
          fi
