name: Build and Push to ECR

on:
  push:
    branches: [ 'feat/meta-358/main' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: keycloak
            context: packages
            file: Dockerfile.keycloak
          - service: frontend
            context: packages
            file: Dockerfile
          - service: harvest
            context: packages/harvest
            file: Dockerfile
          - service: braid
            context: packages/braid
            file: Dockerfile
          - service: windmill
            context: packages/windmill
            file: Dockerfile
      fail-fast: false

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push to ECR
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.file }}
        push: true
        tags: ${{ secrets.AWS_PROD_REGISTRY }}/${{ matrix.service }}:${{ github.sha }}
        build-args: |
          ENVIRONMENT=prod
        cache-from: type=gha,scope=${{ matrix.service }}
        cache-to: type=gha,mode=max,scope=${{ matrix.service }}

    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -t ${{ steps.login-ecr.outputs.registry }}/repo-name/${{ matrix.service }}:${{ github.sha }} -f Dockerfile.${{ matrix.service }} .
    #     docker push ${{ steps.login-ecr.outputs.registry }}/repo-name/${{ matrix.service }}:${{ github.sha }}

    # Add any other necessary steps (like testing or additional validations) here