name: Build and Push to ECR

on:
  pull_request:
  push:
    branches: [ 'main' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: keycloak
            context: packages
            file: packages/Dockerfile.keycloak
            
          - service: voting-portal
            context: packages
            file: packages/Dockerfile.prod
            spa_name: "voting-portal"
            
          - service: admin-portal
            context: packages
            file: packages/Dockerfile.prod
            spa_name: "admin-portal"

          - service: ballot-verifier
            context: packages
            file: packages/Dockerfile.prod
            spa_name: "ballot-verifier"

          - service: harvest
            context: packages
            file: packages/harvest/Dockerfile.prod
            
          - service: braid
            context: packages
            file: packages/braid/Dockerfile.prod
            
          - service: windmill
            context: packages
            file: packages/windmill/Dockerfile.prod
            
      fail-fast: false

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push to ECR
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.file }}
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ${{ secrets.AWS_PROD_REGISTRY }}/${{ matrix.service }}:${{ github.sha }}
        cache-from: type=gha,scope=${{ matrix.service }}
        cache-to: type=gha,mode=max,scope=${{ matrix.service }}
        build-args: SPA_NAME=${{ matrix.spa_name }}

  # rust-fmt:
  #   name: Check Rust format 
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - service: braid
  #         - service: harvest
  #         - service: strand
  #         - service: immu-board
  #         - service: immudb-rs
  #         - service: sequent-core
  #         - service: ballot-verifier
  #         - service: board-messages
  #         - service: velvet
  #         - service: windmill
  #         - service: wrap-map-err
            
  #     fail-fast: false
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Install Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: nightly
  #         components: rustfmt
  #         override: true

  #     - name: Check Rust code formatting
  #       with:
  #         context: ${{ matrix.context }}
  #       run: cd packages/${{ matrix.service }} && cargo fmt -- --check

  rust-ci:
    name: Run Rust tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: braid
          - service: harvest
          - service: strand
          - service: immu-board
          - service: immudb-rs
          - service: sequent-core
          - service: ballot-verifier
          - service: board-messages
          - service: velvet
          - service: windmill
          - service: wrap-map-err
            
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chromium protobuf-compiler libprotobuf-dev
          version: 1.0

      # - name: Run tests
      #   with:
      #     context: ${{ matrix.context }}
      #   run: cd packages/${{ matrix.service }} && cargo test

  # frontend-formatting:
  #   name: Check frontend linting
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - service: braid
  #         - service: harvest
  #         - service: strand
  #         - service: immu-board
  #         - service: immudb-rs
  #         - service: sequent-core
  #         - service: ballot-verifier
  #         - service: board-messages
  #         - service: velvet
  #         - service: windmill
  #         - service: wrap-map-err
            
  #     fail-fast: false
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Set Node.js 20.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.x

  #     - name: Run install
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: install # will run `yarn install` command
  #         dir: packages/

  #     - name: Build ui-essentials
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: build:ui-essentials
  #         dir: packages/

  #     - name: Lint
  #       uses: borales/actions-yarn@v4
  #       with:
  #         context: ${{ matrix.context }}
  #         cmd: lint
  #         dir: packages/${{ matrix.service }}

  #     - name: Prettify
  #       uses: borales/actions-yarn@v4
  #       with:
  #         context: ${{ matrix.context }}
  #         cmd: prettify
  #         dir: packages/${{ matrix.service }}
