# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
# SPDX-License-Identifier: AGPL-3.0-only

name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLA:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The GitHub personal access token (PAT) that has write access to the CLA document repository
          # This should be a PAT from a bot account with write access to the repository
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        with:
          # Path to the CLA document in the repository
          path-to-signatures: '.github/cla/signatures.json'
          path-to-document: 'https://github.com/sequentech/step/blob/main/.github/cla/CLA.md'
          # Branch where CLA signatures will be stored
          branch: 'cla-signatures'
          # Allowlist for bots and automated accounts
          allowlist: 'dependabot*,edulix,Findeton,xalsina-sequent,yuvalkom-M,BelSequent,ereslibre,oded-eid-sequentech'
          
          # Customize the CLA message
          remote-organization-name: 'Sequent Tech Inc'
          remote-repository-name: 'step'
          
          # Customize the message shown to contributors
          custom-pr-sign-comment: 'Thank you for your contribution! Before we can merge this PR, we need you to sign our Contributor License Agreement (CLA).<br/><br/>**To sign the CLA**, please comment on this PR with:<br/>`I have read the CLA Document and I hereby sign the CLA`<br/><br/>This is a one-time requirement. Once you have signed, all future contributions will be covered.<br/><br/>You can read the full CLA document here: https://github.com/sequentech/step/blob/main/.github/cla/CLA.md'
          
          custom-allsigned-prcomment: 'All contributors have signed the CLA. âœ…'
          
          lock-pullrequest-aftermerge: false
