name: Generate API Documentation
on:
    pull_request:
    push:
      branches: [ 'main' ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install
      working-directory: ./packages/api-docs/graphql

    - name: Set Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Generate GraphQL documentation
      run: yarn run generate-full-docs
      working-directory: ./packages/api-docs/graphql

    - name: Commit changes
      run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add static/blog.json
          git commit -m "Update blog.json"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}