# SPDX-FileCopyrightText: 2025 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Generate API Documentation
on:
    pull_request:
    push:
      branches: [ 'main' ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: yarn install
      working-directory: ./packages/api-docs/graphql

    - name: Set Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Generate GraphQL documentation
      run: yarn run generate-full-docs
      working-directory: ./packages/api-docs/graphql

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./packages/api-docs/graphql/docs
        retention-days: 365

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4