# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Lint & Prettify

on:
  pull_request:
  push:
      branches: [ 'main', 'release/[0-9]+.[0-9]+' ]

jobs:
  lint-prettify:
    name: Check frontend linting
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - image=ubuntu24-full-x64
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: packages/

      - name: Build ui-core
        uses: borales/actions-yarn@v4
        with:
          cmd: build:ui-core
          dir: packages/
      
      - name: Build ui-essentials
        uses: borales/actions-yarn@v4
        with:
          cmd: build:ui-essentials
          dir: packages/

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
          dir: packages/

      - name: Prettify
        uses: borales/actions-yarn@v4
        with:
          cmd: prettify
          dir: packages/

  lint-prettify-hasura:
    name: Check Hasura prettify
    runs-on:
      - env=infra-euw1
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - image=ubuntu24-full-x64
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: hasura/

      - name: Prettify
        uses: borales/actions-yarn@v4
        with:
          cmd: prettify
          dir: hasura/

  rust-fmt:
    name: Check Rust format 
    runs-on:
      - env=infra-euw1
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - image=ubuntu24-full-x64
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - name: Check Rust code formatting
        run: cd packages/ && cargo fmt -- --check
  
  java-spotless:
    name: Check Java format
    runs-on:
      - env=infra-euw1
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - image=ubuntu24-full-x64
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Spotless Check
        run: cd packages/keycloak-extensions && mvn clean install &&mvn invoker:run@run-spotless-check
