# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Local images Prebuild and Push

on:
  pull_request:
    paths: 
      - '.devcontainer/postgresql/**'
      - '.devcontainer/minio/**'
      - '.devcontainer/vault/**'
      - 'vendor/immudb-log-audit/**'
      - 'packages/Dockerfile.immudb'
      - 'packages/Dockerfile.cargo-packages'
      - 'packages/Dockerfile.keycloak'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Keycloak
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: packages/.
        file: packages/Dockerfile.keycloak
        tags: ghcr.io/${{ github.repository }}/keycloak:latest
        push: true

    - name: Build and push Postgres
      run: |
        cd .devcontainer/postgresql && docker build -t ghcr.io/${{ github.repository }}/postgres:latest -f Dockerfile .
        docker push ghcr.io/${{ github.repository }}/postgres:latest

    - name: Build and push Minio
      run: |
        cd .devcontainer/minio && docker build -t ghcr.io/${{ github.repository }}/minio:latest -f Dockerfile .
        docker push ghcr.io/${{ github.repository }}/minio:latest

    - name: Build and push Vault
      run: |
        cd .devcontainer/vault && docker build -t ghcr.io/${{ github.repository }}/vault:latest -f Dockerfile .
        docker push ghcr.io/${{ github.repository }}/vault:latest

    - name: Build and push cargo packages
      run: |
        cd packages && docker build -t ghcr.io/${{ github.repository }}/cargo-packages:latest -f Dockerfile.cargo-packages .
        docker push ghcr.io/${{ github.repository }}/cargo-packages:latest

    - name: Build and push immudb
      run: |
        cd packages && docker build -t ghcr.io/${{ github.repository }}/immudb:latest -f Dockerfile.immudb .
        docker push ghcr.io/${{ github.repository }}/immudb:latest

    - name: Build and push immudb-log-audit
      run: |
        cd vendor/immudb-log-audit && docker build -t ghcr.io/${{ github.repository }}/immudb-log-audit:latest -f Dockerfile.immudb .
        docker push ghcr.io/${{ github.repository }}/cargo-packages:latest