# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Local images Prebuild and Push

on:
  schedule:
    - cron: "5 0 * * 1-5"
  push:
    branches:
      - "feat/meta-703-jorge/main"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Keycloak
      run: |
        cd packages && docker build -t ghcr.io/${{ github.repository }}/keycloak:latest -f Dockerfile.keycloak .
        docker push ghcr.io/${{ github.repository }}/keycloak:latest

    - name: Build and push Postgres
      run: |
        cd .devcontainer/postgres && docker build -t ghcr.io/${{ github.repository }}/postgres:latest -f Dockerfile .
        docker push ghcr.io/${{ github.repository }}/postgres:latest

    - name: Build and push Minio
      run: |
        cd .devcontainer/minio && docker build -t ghcr.io/${{ github.repository }}/minio:latest -f Dockerfile .
        docker push ghcr.io/${{ github.repository }}/minio:latest

    - name: Build and push Vault
      run: |
        cd .devcontainer/vault && docker build -t ghcr.io/${{ github.repository }}/vault:latest -f Dockerfile .
        docker push ghcr.io/${{ github.repository }}/vault:latest

    - name: Build and push cargo packages
      run: |
        cd packages && docker build -t ghcr.io/${{ github.repository }}/cargo-packages:latest -f Dockerfile.cargo-packages .
        docker push ghcr.io/${{ github.repository }}/cargo-packages:latest