# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Tests

on:
  pull_request:
  push:
    branches: [ 'main' ]

jobs:
  run-tests:
    name: Run Rust tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          #- service: braid # these take too long!
          - service: harvest
            extra:
          - service: strand
            extra:
          - service: immu-board
            extra:
          - service: immudb-rs
            extra:
          - service: sequent-core
            extra: --features keycloak
          - service: board-messages
            extra:
          - service: velvet
            extra:
          - service: windmill
            extra:
          - service: wrap-map-err
            extra:
  
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-02-22
          components: rustfmt
          override: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chromium protobuf-compiler libprotobuf-dev
          version: 1.0

      - name: Run tests
        env:
          RUST_BACKTRACE: "full"
          KEYCLOAK_DB__USER: "test"
          KEYCLOAK_DB__PASSWORD: "test"
          KEYCLOAK_DB__HOST: "test"
          KEYCLOAK_DB__PORT: "3322"
          KEYCLOAK_DB__DBNAME: "test"
          KEYCLOAK_DB__MANAGER__RECYCLING_METHOD: "Verified"
          HASURA_DB__USER: "test"
          HASURA_DB__PASSWORD: "test"
          HASURA_DB__HOST: "test"
          HASURA_DB__PORT: "3322"
          HASURA_DB__DBNAME: "test"
          HASURA_DB__MANAGER__RECYCLING_METHOD: "Verified"
          LOW_SQL_LIMIT: "1000"
          DEFAULT_SQL_LIMIT: "20"
          DEFAULT_SQL_BATCH_SIZE: "1000"

        run: cd packages/${{ matrix.service }} && cargo test {{ matrix.extra }}