# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Tests

on:
  pull_request:
  push:
    branches: [ 'main', 'release/[0-9]+.[0-9]+' ]

jobs:
  run-tests:
    name: Run Rust tests
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - image=ubuntu24-full-x64
    strategy:
      matrix:
        include:
          #- service: braid # these take too long!
          - service: harvest
          - service: strand
          - service: immu-board
          - service: immudb-rs
          - service: sequent-core
            extra: --features keycloak
          - service: velvet
          - service: windmill
          - service: wrap-map-err

      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          target: x86_64-unknown-linux-musl

      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler libprotobuf-dev

      - name: Run tests
        env:
          RUST_BACKTRACE: "full"
          PROTOC: "/usr/bin/protoc"
          KEYCLOAK_DB__USER: "test"
          KEYCLOAK_DB__PASSWORD: "test"
          KEYCLOAK_DB__HOST: "test"
          KEYCLOAK_DB__PORT: "3322"
          KEYCLOAK_DB__DBNAME: "test"
          KEYCLOAK_DB__MANAGER__RECYCLING_METHOD: "Verified"
          HASURA_DB__USER: "test"
          HASURA_DB__PASSWORD: "test"
          HASURA_DB__HOST: "test"
          HASURA_DB__PORT: "3322"
          HASURA_DB__DBNAME: "test"
          HASURA_DB__MANAGER__RECYCLING_METHOD: "Verified"
          LOW_SQL_LIMIT: "1000"
          DEFAULT_SQL_LIMIT: "20"
          DEFAULT_SQL_BATCH_SIZE: "1000"
        run: cd packages/${{ matrix.service }} && cargo test ${{ matrix.extra }}
