name: Tests

on:
  pull_request:
  push:
    branches: [ 'main' ]

jobs:
  rust-ci:
    name: Run Rust tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          #- service: braid # these take too long!
          - service: harvest
          - service: strand
          - service: immu-board
          - service: immudb-rs
          - service: sequent-core
          - service: board-messages
          - service: velvet
          - service: windmill
          - service: wrap-map-err
  
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chromium protobuf-compiler libprotobuf-dev
          version: 1.0

      - name: Run tests
        run: cd packages/${{ matrix.service }} && cargo test