# SPDX-FileCopyrightText: 2023-2024 Sequent Tech <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

spectaql:
  targetDir: './docs'
  faviconFile: '../packages/admin-portal/public/sequent.png'
  logoFile: '../packages/admin-portal/public/Sequent_logo_small.png'

introspection:
  schemaFile: "./docs/processed-schema.graphql"
  # url: "http://graphql-engine:8080/v1/graphql"
  headers:
    x-hasura-admin-secret: "admin"

template:
  name: "spectaql"

info:
  title: "Sequent Voting Platform GraphQL API Documentation"
  description: "Detailed description of the API"
  version: "1.0.0"
  x-url: "https://sequentech.io"
